version: '3'

services:
  app-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  app-db-data:
  test-db-data:
